version: "2"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes: 
      - grafana-storage:/var/lib/grafana
    networks:
      - roiter-project
    ports:
      - "3000:3000"     
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - roiter-project
    volumes:
      - ./prometheus:/etc/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  docker-exporter:
    container_name: docker-exporter
    hostname: docker-exporter
    image: prometheusnet/docker_exporter:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9417:9417
    restart: always
  app:
    image: matheusmedrado2020/controll-app
    hostname: app
    container_name: app
    networks:
      - roiter-project
    ports:
      - 80:80
networks:
    roiter-project:
        driver: bridge
volumes:
  grafana-storage:

