global:
  scrape_interval:     5s
  evaluation_interval: 5s
  scrape_timeout:      5s
  external_labels:
    monitor: 'node'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'my_docker_metrics'
    static_configs:
      - targets: ['docker-exporter:9417']
  # - job_name: 'app'
  #   static_configs:
  #     - targets: ['app:80']